export const countryList = [
  { id: 1, name: "Albania" },
  { id: 2, name: "Åland Islands" },
  { id: 3, name: "Algeria" },
  { id: 4, name: "American Samoa" },
  { id: 5, name: "Andorra" },
  { id: 6, name: "Angola" },
  { id: 7, name: "Anguilla" },
  { id: 8, name: "Antarctica" },
  { id: 9, name: "Antigua And Barbuda" },
  { id: 10, name: "Argentina" },
  { id: 11, name: "Armenia" },
  { id: 12, name: "Aruba" },
  { id: 13, name: "Australia" },
  { id: 14, name: "Austria" },
  { id: 15, name: "Azerbaijan" },
  { id: 16, name: "Bahamas" },
  { id: 17, name: "Bahrain" },
  { id: 18, name: "Bangladesh" },
  { id: 19, name: "Barbados" },
  { id: 20, name: "Belarus" },
  { id: 21, name: "Belgium" },
  { id: 22, name: "Belize" },
  { id: 23, name: "Benin" },
  { id: 24, name: "Bermuda" },
  { id: 25, name: "Bhutan" },
  { id: 26, name: "Bolivia (Plurinational State Of" },
  { id: 27, name: "Bonaire, Sint Eustatius And Saba" },
  { id: 28, name: "Bosnia And Herzegovina" },
  { id: 29, name: "Botswana" },
  { id: 30, name: "Bouvet Island" },
  { id: 31, name: "Brazil" },
  { id: 32, name: "British Indian Ocean Territory" },
  { id: 33, name: "Brunei Darussalam" },
  { id: 34, name: "Bulgaria" },
  { id: 35, name: "Burkina Faso" },
  { id: 36, name: "Burundi" },
  { id: 37, name: "Cabo Verde" },
  { id: 38, name: "Cambodia" },
  { id: 39, name: "Cameroon" },
  { id: 40, name: "Canada" },
  { id: 41, name: "Cayman Islands" },
  { id: 42, name: "Central African Republic" },
  { id: 43, name: "Chad" },
  { id: 44, name: "Chile" },
  { id: 45, name: "China" },
  { id: 46, name: "Christmas Island" },
  { id: 47, name: "Cocos (Keeling Islands" },
  { id: 48, name: "Colombia" },
  { id: 49, name: "Comoros" },
  { id: 50, name: "Democratic Republic Of The Congo" },
  { id: 51, name: "Congo" },
  { id: 52, name: "Cook Islands" },
  { id: 53, name: "Costa Rica" },
  { id: 54, name: "Croatia" },
  { id: 55, name: "Cuba" },
  { id: 56, name: "Curaçao" },
  { id: 57, name: "Cyprus" },
  { id: 58, name: "Czechia" },
  { id: 59, name: "Côte D'Ivoire" },
  { id: 60, name: "Denmark" },
  { id: 61, name: "Djibouti" },
  { id: 62, name: "Dominica" },
  { id: 63, name: "Dominican Republic" },
  { id: 64, name: "Ecuador" },
  { id: 65, name: "Egypt" },
  { id: 66, name: "El Salvador" },
  { id: 67, name: "Equatorial Guinea" },
  { id: 68, name: "Eritrea" },
  { id: 69, name: "Estonia" },
  { id: 70, name: "Eswatini" },
  { id: 71, name: "Ethiopia" },
  { id: 72, name: "Falkland Islands (Malvinas" },
  { id: 73, name: "Faroe Islands" },
  { id: 74, name: "Fiji" },
  { id: 75, name: "Finland" },
  { id: 76, name: "France" },
  { id: 77, name: "French Guiana" },
  { id: 78, name: "French Polynesia" },
  { id: 79, name: "French Southern Territories" },
  { id: 80, name: "Gabon" },
  { id: 81, name: "Gambia" },
  { id: 82, name: "Georgia" },
  { id: 83, name: "Germany" },
  { id: 84, name: "Ghana" },
  { id: 85, name: "Gibraltar" },
  { id: 86, name: "Greece" },
  { id: 87, name: "Greenland" },
  { id: 88, name: "Grenada" },
  { id: 89, name: "Guadeloupe" },
  { id: 90, name: "Guam" },
  { id: 91, name: "Guatemala" },
  { id: 92, name: "Guernsey" },
  { id: 93, name: "Guinea" },
  { id: 94, name: "Guinea-Bissau" },
  { id: 95, name: "Guyana" },
  { id: 96, name: "Haiti" },
  { id: 97, name: "Heard Island And McDonald Islands" },
  { id: 98, name: "Holy See" },
  { id: 99, name: "Honduras" },
  { id: 100, name: "Hong Kong" },
  { id: 101, name: "Hungary" },
  { id: 102, name: "Iceland" },
  { id: 103, name: "India" },
  { id: 104, name: "Indonesia" },
  { id: 105, name: "Iran (Islamic Republic Of" },
  { id: 106, name: "Iraq" },
  { id: 107, name: "Ireland" },
  { id: 108, name: "Isle Of Man" },
  { id: 109, name: "Israel" },
  { id: 110, name: "Italy" },
  { id: 111, name: "Jamaica" },
  { id: 112, name: "Japan" },
  { id: 113, name: "Jersey" },
  { id: 114, name: "Jordan" },
  { id: 115, name: "Kazakhstan" },
  { id: 116, name: "Kenya" },
  { id: 117, name: "Kiribati" },
  { id: 118, name: "Korea (Democratic People's Republic Of Korea" },
  { id: 119, name: "Republic Of Korea" },
  { id: 120, name: "Kuwait" },
  { id: 121, name: "Kyrgyzstan" },
  { id: 122, name: "Lao People's Democratic Republic" },
  { id: 123, name: "Latvia" },
  { id: 124, name: "Lebanon" },
  { id: 125, name: "Lesotho" },
  { id: 126, name: "Liberia" },
  { id: 127, name: "Libya" },
  { id: 128, name: "Liechtenstein" },
  { id: 129, name: "Lithuania" },
  { id: 130, name: "Luxembourg" },
  { id: 131, name: "Macao" },
  { id: 132, name: "Madagascar" },
  { id: 133, name: "Malawi" },
  { id: 134, name: "Malaysia" },
  { id: 135, name: "Maldives" },
  { id: 136, name: "Mali" },
  { id: 137, name: "Malta" },
  { id: 138, name: "Marshall Islands" },
  { id: 139, name: "Martinique" },
  { id: 140, name: "Mauritania" },
  { id: 141, name: "Mauritius" },
  { id: 142, name: "Mayotte" },
  { id: 143, name: "Mexico" },
  { id: 144, name: "Micronesia (Federated States Of" },
  { id: 145, name: "Republic Of Moldova" },
  { id: 146, name: "Monaco" },
  { id: 147, name: "Mongolia" },
  { id: 148, name: "Montenegro" },
  { id: 149, name: "Montserrat" },
  { id: 150, name: "Morocco" },
  { id: 151, name: "Mozambique" },
  { id: 152, name: "Myanmar" },
  { id: 153, name: "Namibia" },
  { id: 154, name: "Nauru" },
  { id: 155, name: "Nepal" },
  { id: 156, name: "Netherlands" },
  { id: 157, name: "New Caledonia" },
  { id: 158, name: "New Zealand" },
  { id: 159, name: "Nicaragua" },
  { id: 160, name: "Niger" },
  { id: 161, name: "Nigeria" },
  { id: 162, name: "Niue" },
  { id: 163, name: "Norfolk Island" },
  { id: 164, name: "Northern Mariana Islands" },
  { id: 165, name: "Norway" },
  { id: 166, name: "Oman" },
  { id: 167, name: "Pakistan" },
  { id: 168, name: "Palau" },
  { id: 169, name: "State Of Palestine" },
  { id: 170, name: "Panama" },
  { id: 171, name: "Papua New Guinea" },
  { id: 172, name: "Paraguay" },
  { id: 173, name: "Peru" },
  { id: 174, name: "Philippines" },
  { id: 175, name: "Pitcairn" },
  { id: 176, name: "Poland" },
  { id: 177, name: "Portugal" },
  { id: 178, name: "Puerto Rico" },
  { id: 179, name: "Qatar" },
  { id: 180, name: "Republic Of North Macedonia" },
  { id: 181, name: "Romania" },
  { id: 182, name: "Russian Federation" },
  { id: 183, name: "Rwanda" },
  { id: 184, name: "Réunion" },
  { id: 185, name: "Saint Barthélemy" },
  { id: 186, name: "Saint Helena, Ascension And Tristan da Cunha" },
  { id: 187, name: "Saint Kitts And Nevis" },
  { id: 188, name: "Saint Lucia" },
  { id: 189, name: "Saint Martin (French part" },
  { id: 190, name: "Saint Pierre And Miquelon" },
  { id: 191, name: "Saint Vincent And the Grenadines" },
  { id: 192, name: "Samoa" },
  { id: 193, name: "San Marino" },
  { id: 194, name: "Sao Tome And Principe" },
  { id: 195, name: "Saudi Arabia" },
  { id: 196, name: "Senegal" },
  { id: 197, name: "Serbia" },
  { id: 198, name: "Seychelles" },
  { id: 199, name: "Sierra Leone" },
  { id: 200, name: "Singapore" },
  { id: 201, name: "Sint Maarten (Dutch part" },
  { id: 202, name: "Slovakia" },
  { id: 203, name: "Slovenia" },
  { id: 204, name: "Solomon Islands" },
  { id: 205, name: "Somalia" },
  { id: 206, name: "South Africa" },
  { id: 207, name: "South Georgia And the South Sandwich Islands" },
  { id: 208, name: "South Sudan" },
  { id: 209, name: "Spain" },
  { id: 210, name: "Sri Lanka" },
  { id: 211, name: "Sudan" },
  { id: 212, name: "Suriname" },
  { id: 213, name: "Svalbard And Jan Mayen" },
  { id: 214, name: "Sweden" },
  { id: 215, name: "Switzerland" },
  { id: 216, name: "Syrian Arab Republic" },
  { id: 217, name: "Taiwan, Province Of China" },
  { id: 218, name: "Tajikistan" },
  { id: 219, name: "United Republic Of Tanzania" },
  { id: 220, name: "Thailand" },
  { id: 221, name: "Timor-Leste" },
  { id: 222, name: "Togo" },
  { id: 223, name: "Tokelau" },
  { id: 224, name: "Tonga" },
  { id: 225, name: "Trinidad And Tobago" },
  { id: 226, name: "Tunisia" },
  { id: 227, name: "Turkey" },
  { id: 228, name: "Turkmenistan" },
  { id: 229, name: "Turks And Caicos Islands" },
  { id: 230, name: "Tuvalu" },
  { id: 231, name: "Uganda" },
  { id: 232, name: "Ukraine" },
  { id: 233, name: "United States Of America" },
  { id: 234, name: "United Kingdom Of Great Britain And Northern Ireland" },
  { id: 235, name: "United States Minor Outlying Islands" },
  { id: 236, name: "United Arab Emirates" },
  { id: 237, name: "Uruguay" },
  { id: 238, name: "Uzbekistan" },
  { id: 239, name: "Vanuatu" },
  { id: 240, name: "Venezuela (Bolivarian Republic Of Venezuela" },
  { id: 241, name: "Viet Nam" },
  { id: 242, name: "Virgin Islands (British" },
  { id: 243, name: "Virgin Islands (U.S." },
  { id: 244, name: "Wallis And Futuna" },
  { id: 245, name: "Western Sahara" },
  { id: 246, name: "Yemen" },
  { id: 247, name: "Zambia" },
  { id: 248, name: "Zimbabwe" },
];
